# --- Database ---
POSTGRES_USER={{DB_USER}}
POSTGRES_PASSWORD={{DB_PASSWORD}}
POSTGRES_DB={{DB_NAME}}
POSTGRES_PORT={{DB_PORT_EXTERNAL}}

# --- NextAuth ---
NEXTAUTH_SECRET={{NEXTAUTH_SECRET}}
NEXT_PUBLIC_APP_URL={{NEXT_APP_URL}}

# --- Email (Mailpit Internal) ---
EMAIL_SERVER_HOST={{EMAIL_HOST_DOCKER}}
EMAIL_SERVER_PORT=1025
EMAIL_SERVER_USER=none
EMAIL_SERVER_PASSWORD=none
EMAIL_FROM={{EMAIL_FROM}}

# --- Docker ---
DOCKER_IMAGE_NAME={{DOCKER_IMAGE_NAME}}
